[workspace]
members = [
    "rust/botl-pdf-core",
    "rust/botl-pdf-csys",
    "rust/botl-pdf-python",
]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2021"
rust-version = "1.80"
license = "Apache-2.0"
repository = "https://github.com/Shivamjohri247/botl-pdf"

[workspace.dependencies]
pyo3 = { version = "0.23", features = ["abi3-py38"] }
parking_lot = "0.12"
nom = "7"
flate2 = { version = "1", default-features = false, features = ["zlib-ng"] }
ring = "0.17"
encoding_rs = "0.8"
hashbrown = "0.15"
smallvec = "1"
bumpalo = "3"
rstar = "0.12"
memmap2 = "0.9"
thiserror = "2"
