"""Type stubs for the botl_pdf._core native module (generated by PyO3)."""

from typing import Optional


class PyBBox:
    x0: float
    y0: float
    x1: float
    y1: float

    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...

    def center(self) -> tuple[float, float]: ...
    def area(self) -> float: ...
    def __repr__(self) -> str: ...


class PyChar:
    text: str
    bbox: PyBBox
    font_name: str
    font_size: float
    bold: bool
    italic: bool
    color: Optional[tuple[float, float, float]]
    stroking_color: Optional[tuple[float, float, float]]
    rotation: float


class PyWord:
    text: str
    bbox: PyBBox
    chars: list[PyChar]
    direction: str
    font_name: str
    font_size: float

    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


class PyTextLine:
    words: list[PyWord]
    bbox: PyBBox
    text: str


class PyTextBlock:
    lines: list[PyTextLine]
    bbox: PyBBox
    text: str


class PyTOCEntry:
    title: str
    level: int
    page_number: int
    dest: Optional[str]


class PyGeomLine:
    x0: float
    y0: float
    x1: float
    y1: float
    line_width: float
    color: Optional[tuple[float, float, float]]


class PyGeomRect:
    bbox: PyBBox
    line_width: float
    stroke_color: Optional[tuple[float, float, float]]
    fill_color: Optional[tuple[float, float, float]]


class PyLayoutParams:
    word_margin: float
    line_margin: float
    boxes_flow: float


class PyPage:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def rotation(self) -> int: ...
    @property
    def page_number(self) -> int: ...
    @property
    def label(self) -> str: ...

    def extract_text(
        self,
        layout: bool = False,
        layout_params: Optional[PyLayoutParams] = None,
    ) -> str: ...

    @property
    def chars(self) -> list[PyChar]: ...
    @property
    def lines(self) -> list[PyGeomLine]: ...
    @property
    def rects(self) -> list[PyGeomRect]: ...


class PyDocument:
    @property
    def metadata(self) -> dict[str, Optional[str]]: ...
    @property
    def num_pages(self) -> int: ...
    @property
    def is_encrypted(self) -> bool: ...
    @property
    def toc(self) -> list[PyTOCEntry]: ...

    def get_page(self, index: int) -> PyPage: ...
    def __getitem__(self, index: int) -> PyPage: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...


class PyWriter:
    def __init__(self) -> None: ...


def open(
    path_or_bytes: str | bytes,
    password: Optional[str] = None,
    lazy: bool = True,
) -> PyDocument: ...
