import { useState, useCallback, useRef, useEffect } from 'react'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import PDFViewer from './components/PDFViewer'
import RightPanel from './components/RightPanel'
import Toolbar from './components/Toolbar'
import MergeDialog from './components/MergeDialog'
import { NotificationProvider, useNotifications } from './contexts/NotificationContext'
import { ToastContainer } from './components/Notifications'

// Import Wails bindings - generated by wails dev/build
import { OpenFilePicker, SaveFileDialog, ReadFileAsBase64 } from '../wailsjs/go/backend/App'

export interface PDFFile {
  id: string
  name: string
  pages: number
  size: number
  path?: string          // URL for viewing (blob, data URL, etc.)
  originalPath?: string  // Original file path for operations (merge, split, etc.)
  file?: File
}

export interface PageThumbnail {
  pageNumber: number
  active: boolean
}

function AppContent() {
  const { addNotification } = useNotifications()
  const [pdfFiles, setPdfFiles] = useState<PDFFile[]>([])
  const [activePdfId, setActivePdfId] = useState<string | null>(null)
  const [currentPage, setCurrentPage] = useState(1)
  const [totalPages, setTotalPages] = useState(0)
  const [zoom, setZoom] = useState(100)
  const [rotation, setRotation] = useState(0)
  const [currentTool, setCurrentTool] = useState<'select' | 'text' | 'highlight'>('select')
  const [isEditMode, setIsEditMode] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  const [isMergeDialogOpen, setIsMergeDialogOpen] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const activePdf = pdfFiles.find(f => f.id === activePdfId) ?? null

  // Update total pages when active PDF changes
  const handlePDFLoadSuccess = useCallback((numPages: number) => {
    setTotalPages(numPages)
    if (activePdfId) {
      setPdfFiles(prev => prev.map(f =>
        f.id === activePdfId ? { ...f, pages: numPages } : f
      ))
    }
  }, [activePdfId])

  const handleAddPDF = useCallback(async (files: File[] | string[]) => {
    const newFiles: PDFFile[] = []

    for (const file of files) {
      let fileName: string
      let fileSize: number
      let filePath: string
      let originalPath: string | undefined
      let fileObj: File | undefined

      if (typeof file === 'string') {
        // File path from Wails file picker - need to convert to data URL
        originalPath = file // Store original path for operations
        try {
          const dataUrl = await ReadFileAsBase64(file)
          filePath = dataUrl
          fileName = file.split('/').pop() || file.split('\\').pop() || 'document.pdf'
          fileSize = 0 // Will be determined by file system
        } catch (error) {
          console.error('Failed to read file:', error)
          continue
        }
      } else {
        // File object from drag & drop or HTML input
        fileName = file.name
        fileSize = file.size
        filePath = URL.createObjectURL(file)
        fileObj = file
      }

      const newFile: PDFFile = {
        id: Date.now().toString() + Math.random(),
        name: fileName,
        pages: 1, // Will be updated when PDF loads
        size: fileSize,
        path: filePath,
        originalPath: originalPath, // For merge/split operations
        file: fileObj,
      }
      newFiles.push(newFile)
    }

    setPdfFiles(prev => [...prev, ...newFiles])
    if (newFiles.length > 0 && !activePdfId) {
      setActivePdfId(newFiles[0].id)
    }
  }, [activePdfId])

  const handleRemovePDF = useCallback((id: string) => {
    setPdfFiles(prev => {
      const filtered = prev.filter(f => f.id !== id)
      // Revoke the blob URL to free memory
      const fileToRemove = prev.find(f => f.id === id)
      if (fileToRemove?.path?.startsWith('blob:')) {
        URL.revokeObjectURL(fileToRemove.path)
      }
      return filtered
    })
    if (activePdfId === id) {
      const remaining = pdfFiles.filter(f => f.id !== id)
      setActivePdfId(remaining.length > 0 ? remaining[0].id : null)
      setTotalPages(remaining.length > 0 ? remaining[0].pages : 0)
      setCurrentPage(1)
      setRotation(0)
      setZoom(100)
    }
  }, [activePdfId, pdfFiles])

  const handleSelectPDF = useCallback((id: string) => {
    setActivePdfId(id)
    const pdf = pdfFiles.find(f => f.id === id)
    if (pdf) {
      setTotalPages(pdf.pages)
      setCurrentPage(1)
      setRotation(0)
      setZoom(100)
    }
  }, [pdfFiles])

  const handleToolChange = useCallback((tool: 'select' | 'text' | 'highlight') => {
    setCurrentTool(tool)
    setIsEditMode(tool === 'text')
  }, [])

  const handleRotate = useCallback((degrees: number) => {
    setRotation(prev => (prev + degrees) % 360)
  }, [])

  const handleZoomIn = useCallback(() => {
    setZoom(prev => Math.min(prev + 25, 200))
  }, [])

  const handleZoomOut = useCallback(() => {
    setZoom(prev => Math.max(prev - 25, 50))
  }, [])

  const handleZoomFit = useCallback(() => {
    setZoom(100)
    setRotation(0)
  }, [])

  // Drag and drop handlers
  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }, [])

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    const files = Array.from(e.dataTransfer.files)
    handleAddPDF(files)
  }, [handleAddPDF])

  // Handle opening files via native file dialog
  const handleOpen = useCallback(async () => {
    try {
      const filePaths = await OpenFilePicker()
      if (filePaths && filePaths.length > 0) {
        handleAddPDF(filePaths)
      }
    } catch (error) {
      console.error('Failed to open files:', error)
      // Fallback to HTML file input
      fileInputRef.current?.click()
    }
  }, [handleAddPDF])

  // Handle save
  const handleSave = useCallback(async () => {
    if (!activePdf) return
    try {
      const savePath = await SaveFileDialog(activePdf.name)
      if (savePath) {
        console.log('Save to:', savePath)
        // TODO: Implement actual save logic
      }
    } catch (error) {
      console.error('Failed to save:', error)
    }
  }, [activePdf])

  // Handle export
  const handleExport = useCallback(() => {
    console.log('Export PDF')
    // TODO: Implement export logic
  }, [])

  // Handle merge dialog
  const handleMerge = useCallback(() => {
    setIsMergeDialogOpen(true)
  }, [])

  const handleMergeSuccess = useCallback(() => {
    addNotification({
      type: 'success',
      title: 'Merge Complete',
      message: `${pdfFiles.length} PDFs merged successfully`,
    })
  }, [addNotification, pdfFiles.length])

  return (
    <div className="h-screen flex flex-col bg-primary-bg">
      {/* Hidden file input for fallback */}
      <input
        ref={fileInputRef}
        type="file"
        accept="application/pdf"
        multiple
        className="hidden"
        onChange={(e) => {
          const files = e.target.files
          if (files && files.length > 0) {
            handleAddPDF(Array.from(files))
          }
        }}
      />

      {/* Fixed Header - h-14 (56px) */}
      <div className="flex-shrink-0">
        <Header
          currentPdf={activePdf}
          onSave={handleSave}
          onExport={handleExport}
        />
      </div>

      <div
        className={`flex-1 flex min-h-0 ${isDragging ? 'bg-accent-green/10' : ''}`}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
      >
        <Sidebar
          pdfFiles={pdfFiles}
          activePdfId={activePdfId}
          currentPage={currentPage}
          totalPages={totalPages}
          onOpenFilePicker={handleOpen}
          onRemovePDF={handleRemovePDF}
          onSelectPDF={handleSelectPDF}
          onSelectPage={setCurrentPage}
        />

        {/* PDF Viewer Area - takes remaining height and handles overflow */}
        <div className="flex-1 flex flex-col relative min-h-0 min-w-0">
          {/* PDF Viewer - scrollable area */}
          <div className="flex-1 overflow-auto min-h-0">
            <PDFViewer
              pdfFile={activePdf}
              currentPage={currentPage}
              zoom={zoom}
              rotation={rotation}
              isEditMode={isEditMode}
              currentTool={currentTool}
              onPageCountChange={handlePDFLoadSuccess}
            />
          </div>

          {/* Drag overlay */}
          {isDragging && (
            <div className="absolute inset-0 bg-accent-green/20 flex items-center justify-center z-50 pointer-events-none">
              <div className="bg-white rounded-lg shadow-lg p-6 flex flex-col items-center">
                <div className="w-16 h-16 bg-accent-green/10 rounded-full flex items-center justify-center mb-3">
                  <svg className="w-8 h-8 text-accent-green" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                  </svg>
                </div>
                <p className="text-text-primary font-medium">Drop PDF files here</p>
              </div>
            </div>
          )}

          {/* Fixed Toolbar - h-12 (48px) */}
          <div className="flex-shrink-0 border-t border-border">
            <Toolbar
              currentTool={currentTool}
              currentPage={currentPage}
              totalPages={totalPages}
              zoom={zoom}
              onToolChange={handleToolChange}
              onPagePrev={() => setCurrentPage(p => Math.max(1, p - 1))}
              onPageNext={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
              onPageJump={setCurrentPage}
              onZoomIn={handleZoomIn}
              onZoomOut={handleZoomOut}
              onZoomFit={handleZoomFit}
              onRotateLeft={() => handleRotate(-90)}
              onRotateRight={() => handleRotate(90)}
            />
          </div>
        </div>

        <RightPanel
          pdfFile={activePdf}
          isEditMode={isEditMode}
          onMerge={handleMerge}
          onSplit={() => console.log('Split')}
          onExtract={() => console.log('Extract')}
          onDelete={() => console.log('Delete')}
          onProtect={() => console.log('Protect')}
          onUnlock={() => console.log('Unlock')}
          onWatermark={() => console.log('Watermark')}
          onCompress={() => console.log('Compress')}
        />
      </div>

      {/* Merge Dialog */}
      <MergeDialog
        isOpen={isMergeDialogOpen}
        onOpenChange={setIsMergeDialogOpen}
        existingFiles={pdfFiles}
        onMergeSuccess={handleMergeSuccess}
      />
    </div>
  )
}

function App() {
  return (
    <NotificationProvider>
      <AppContent />
      <ToastContainer />
    </NotificationProvider>
  )
}

export default App
